### ISSUE TITLE
Support a cleaner API for Istio

### ISSUE THREAD

**Issue by myidpt** [ThalesGroup/k8s-kms-plugin#3]
The current istio/v1 API https://github.com/thalescpl-io/k8s-kms-plugin/blob/master/apis/istio/v1/service.proto#L28 has some issues:

1. Istio doesn't need to understand the encryption / decryption details, so GenerateDEK() isn't needed.
2. We also need an API to sign a cert.
3. General APIs like Encrypt() and Decrypt() may be better for API stability.

This is a proposal to restruct the Istio/v1 API:

GenerateKEK() // Same as today

DestroyKEK() // Same as today

GenerateKey():
  input: key type and parameters.
  output: key in clear text. In Istio case, the signing key.

SignCSR():
  input: CSR.
  output: certificate chain containing the issued certificate

Encrypt():
  input: data blob to be encrypted, KEK ID (required).
  output: encrypted data blob

Decrypt():
  input: encrypted data blob, KEK ID (required)
  output: decrypted data

Note:

1. Alternatively SignCSR() API can be GenerateKeyCert(), which takes all necessary parameters and generates both key and cert. I slightly prefer SignCSR() because CSR is a struct that allows Istio to specify the certificate in a formal way.

2. Encrypt() is needed to encrypt the private key and certificate before writing to the secret.

3. HSM plugin can take the ENV variables for specifying the PKI path, slot PIN, etc.

**Comment by incfly** [comment]
>  so GenerateDEK() isn't needed.

So how will DEK be generated, by Istiod itself? And then call Encrypt to get it protected by KEK?

Another thing worth mentioning, given how many people have questions about `SEK`, and in the API's naming, shall we call it just SigningKey? IOr something else?

**Comment by myidpt** [comment]
I meant the use of DEK is agnostic to Istiod. DEK is the encryption detail managed by the HSM plugin. Istiod only sees either the clear data or the encrypted blob. Does that make sense?

I think as an API the SEK name seems OK, because you can also use this API to generate an encryption key. For the Istio design doc, I agree we should use the SigningKey name to avoid confusion.

**Comment by incfly** [comment]
I remember Istiod at least would store the DEK in memory as plaintext, and use it for other materials encryption/decryption. So it's not transparent and handled by Istiod as well? If no, maybe I should re-read the design again..

**Comment by myidpt** [comment]
No, it shouldn't matter much to you. The DEK is managed by the plugin, which has the same life cycle as the Istiod.

**Comment by solcates** [comment]
@incfly I took a look at the proposed changes above, and normalized it against the Kubernetes Secrets KMS api, and the Google CloudKMS api, so they can be API compatible (paths are different of course as there is no concept of keyrings in a HSM).

All those changes were in commit 91ac305b5dce435615cddf53ac06e388a40d8aaf and is where we'll want to consolidate the client and server API interactions.

I will update the sequence diagrams and add a new Key Architecture document that goes into the details of how the keys in the in the HSM for it's Root of Trust and Data protection needs of all data and key blobs used by the plugin and it's key store.
